# Generated by Django 5.1 on 2024-08-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filmy',
            new_name='Film',
        ),
    ]
