# Generated by Django 5.1 on 2024-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0008_alter_dodatkoweinfo_gatunek_aktor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='opis',
            new_name='recenzja',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inne'), (4, 'Dramat'), (2, 'Komedia'), (3, 'Sci-fi')], default=0),
        ),
    ]
